command_timeout = 3500

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$line_break\
$kubernetes\
$line_break\
$golang\
$python\
$character"""

# Comment/uncomment the lines below to toggle between a loaded and a very minimalist prompt. Good for doing code demos.
# ############################### - from here
# format = """
# $directory \
# $shell \
# """

# [shell]
# fish_indicator = ""
# powershell_indicator = "_"
# unknown_indicator = "mystery shell"
# disabled = false
# ############################### - to here

[status]
style = "bg:black"
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol = "[➜ V](bold purple) "

[directory]
# disabled = true
truncate_to_repo = false
home_symbol = "$HOME"

[cmd_duration]
min_time = 5
format = "took [$duration](bold purple)"

[hostname]
ssh_only = true
format = "[$hostname](red) "
trim_at = ".companyname.com"
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = false

[gcloud]
disabled = true
symbol = "️"

[aws]
disabled = true
format = "[$symbol $region]($style) "
style = "bold blue"
symbol = "🅰 "


[helm]
format = "(bold white) "

[docker_context]
format = "[🐋 $context](blue bold)"

[git_branch]
symbol = "🌱 "
format = "on [$symbol$branch]($style) "

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
only_nonzero_diffs = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[kubernetes]
format = '[$context \($namespace\)](dimmed green) '
# format = '[>$context](dimmed red) [$namespace](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[golang]
# disabled = true
symbol = '🐹 '
style = 'yellow bold'
format = '[$symbol($version )]($style)'

[python]
format = '[🐍 $version](bold green) '

[container]
format = '[$symbol \[$name\]]($style) '
