#!/bin/sh

SESSION="velero"

sessions() {
  echo tmux ls -F '#S'
}

if $(sessions) =~ $SESSION; then
  if [ -n "$TMUX" ]; then
      tmux -2 attach-session -t $SESSION
  else
      tmux switch-client -t $SESSION
  fi
else
  echo creating session $SESSION
  # Create the session (behave like attach-session if session-name already exists)
  tmux -2 new-session -A -d -s $SESSION

  # VELERO WINDOW (1)
  tmux new-window -n velero -t $SESSION
  tmux rename-window -t $SESSION:1 velero
  tmux send-keys -t $SESSION:1 '~' C-m
  tmux send-keys -t $SESSION:1 'clear' C-m
  tmux split-window -h -t $SESSION:1
  # scripts window
  tmux select-pane -t $SESSION:1.0
  tmux resize-pane -R 30
  tmux send-keys -t $SESSION:1.0 'cd /Users/carlisia/velero-scripts' C-m
  tmux send-keys -t $SESSION:1.0 'clear' C-m
  # velero window
  tmux select-pane -t $SESSION:1.1 
  tmux send-keys -t $SESSION:1.1 'cd /Users/carlisia/work/src/github.com/vmware-tanzu/velero' C-m
  tmux send-keys -t $SESSION:1.1 'g' C-m

  # CLEAN WINDOW (2)
  tmux new-window -n aws-staging -t $SESSION
  tmux rename-window -t $SESSION:2 aws-staging
  tmux send-keys -t $SESSION:2 'set -x KUBECONFIG $HOME/.kube/aws-staging' C-m
  tmux send-keys -t $SESSION:2 'clear' C-m

  # KIND+KUBE-PROMPT-WINDOW (3)
  tmux rename-window -t $SESSION:3 kind+kp
  tmux split-window -h -t $SESSION:3
  # kind pane
  tmux select-pane -t $SESSION:3.0
  tmux resize-pane -R 30
  tmux send-keys -t $SESSION:3.0 'clear' C-m
  tmux send-keys -t $SESSION:3.0 'g' C-m
  tmux send-keys -t $SESSION:3.0 'kind get clusters' C-m
  # kube-prompt pane
  tmux send-keys -t $SESSION:3.1 'kube-prompt' C-m

  # DOTFILES WINDOW (4)
  tmux new-window -n dotfiles -t $SESSION
  tmux rename-window -t $SESSION:4 dotfiles
  tmux send-keys -t $SESSION:4 'cd /Users/carlisia/dotfiles' C-m
  tmux send-keys -t $SESSION:4 'clear' C-m
  tmux send-keys -t $SESSION:4 'g' C-m

  # PLUGIN EXAMPLES + COMMUNITY WINDOW (5)
  tmux new-window -n plugin+community -t $SESSION
  tmux rename-window -t $SESSION:5 plugin+community
  # plugin examples pane
  tmux send-keys -t $SESSION:5.0 'cd /Users/carlisia/work/src/github.com/vmware-tanzu/velero-plugin-example' C-m
  tmux send-keys -t $SESSION:5.0 'clear' C-m
  tmux send-keys -t $SESSION:5.0 'g' C-m
  # velero community pane
  tmux send-keys -t $SESSION:5.1 'cd /Users/carlisia/work/src/github.com/vmware-tanzu/velero-community' C-m
  tmux send-keys -t $SESSION:5.1 'clear' C-m
  tmux send-keys -t $SESSION:5.1 'g' C-m

  # DEVELOPMENT WINDOW (6)
  tmux new-window -n DEVELOPMENT -t $SESSION
  tmux rename-window -t $SESSION:6.0 DEVELOPMENT
  tmux split-window -v -t $SESSION:6.0
  # top 
  tmux select-pane -t $SESSION:6.0
  tmux resize-pane -R 80
  tmux send-keys -t $SESSION:6.0 'cd /Users/carlisia/velero-scripts/local-minio' C-m
  tmux send-keys -t $SESSION:6.0 'set -x KUBECONFIG $HOME/.kube/kind-config-development' C-m
  tmux send-keys -t $SESSION:6.0 'clear' C-m
  # bottom pane
  tmux send-keys -t $SESSION:6.1 'cd /Users/carlisia/velero-scripts/local-minio' C-m
  tmux send-keys -t $SESSION:6.1 'set -x KUBECONFIG $HOME/.kube/kind-config-development' C-m
  tmux send-keys -t $SESSION:6.1 'clear' C-m
  tmux select-pane -t $SESSION:6.0

  # STAGING WINDOW (7)
  tmux new-window -n STAGING -t $SESSION
  tmux rename-window -t $SESSION:7.0 STAGING
  tmux split-window -v -t $SESSION:7.0
  # top 
  tmux select-pane -t $SESSION:7.0
  tmux resize-pane -R 80
  tmux send-keys -t $SESSION:7.0 'cd /Users/carlisia/velero-scripts/local-minio' C-m
  tmux send-keys -t $SESSION:7.0 'set -x KUBECONFIG $HOME/.kube/kind-config-staging' C-m
  tmux send-keys -t $SESSION:7.0 'clear' C-m
  # bottom pane
  tmux send-keys -t $SESSION:7.1 'cd /Users/carlisia/velero-scripts/local-minio' C-m
  tmux send-keys -t $SESSION:7.1 'set -x KUBECONFIG $HOME/.kube/kind-config-staging' C-m
  tmux send-keys -t $SESSION:7.1 'clear' C-m
  tmux select-pane -t $SESSION:7.0

  # # THE KUBELETS WINDOW (7)
  # tmux new-window -n kubelets -t $SESSION
  # tmux rename-window -t $SESSION:7 kubelets
  # tmux send-keys -t $SESSION:7 'cd /Users/carlisia/work/src/github.com/vmware-tanzu/thekubelets' C-m
  # tmux send-keys -t $SESSION:7 'clear' C-m
  # tmux send-keys -t $SESSION:7 'g' C-m

  # EKS WINDOW (8)
  tmux new-window -n STAGING -t $SESSION
  tmux rename-window -t $SESSION:7.0 STAGING
  tmux split-window -v -t $SESSION:7.0
  # top 
  tmux select-pane -t $SESSION:7.0
  tmux resize-pane -R 80
  tmux send-keys -t $SESSION:7.0 'cd /Users/carlisia/velero-scripts/local-minio' C-m
  tmux send-keys -t $SESSION:7.0 'set -x KUBECONFIG $HOME/.kube/kind-config-staging' C-m
  tmux send-keys -t $SESSION:7.0 'clear' C-m
  # bottom pane
  tmux send-keys -t $SESSION:7.1 'cd /Users/carlisia/velero-scripts/local-minio' C-m
  tmux send-keys -t $SESSION:7.1 'set -x KUBECONFIG $HOME/.kube/kind-config-staging' C-m
  tmux send-keys -t $SESSION:7.1 'clear' C-m
  tmux select-pane -t $SESSION:7.0

  # CLEAN: OCTANT WINDOW (8)
  tmux new-window -n sl -t $SESSION
  tmux rename-window -t $SESSION:8 octant

  # K9S WINDOW (9)
  tmux new-window -n k9s -t $SESSION
  tmux rename-window -t $SESSION:9 k9s
  tmux send-keys -t $SESSION:9 'clear' C-m
  tmux send-keys -t $SESSION:9 'k9s' C-m

  # Start out on the first window when we attach
  tmux select-window -t $SESSION:1
  tmux switch-client -t $SESSION
  tmux -2 attach-session -t $SESSION:1
fi