version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - revive
    - gosimple
    - unused
  settings:
    govet:
      enable:
        - inline
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unreachable-code
        - name: unused-parameter
